# Display message to the standard output
print("System Failure Imminent!")
print("System reboot has been initiated...")
print("")
print("")
print("...Rebooting sensory system")
print("...Rebooting output motors")
print("...Rebooting hover engine")
print("")
print("System online.")
print("\t\"I am Beep\"")
